title: 我的信息安全攻防指南
description: Web安全,企业安全,内网渗透,安全开发,安全运维,渗透测试,代码审计
author: Weiho
github: https://github.com/zhaoweiho
about: Life is stuggle,try everything
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-weibo
      link: "https://weibo.com/l4c1fer"
    - icon: fa-twitter
      link: "https://twitter.com/Weiho14"
    - icon: fa-instagram
      link: "https://www.instagram.com/weiho.zhao/"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/%E8%B6%99%E9%9F%AA%E7%81%8FWeiho/"
    - icon: fa-github
      link: "https://github.com/zhaoweiho"

urls:
    - text: 分类
      url: /categories/
    - text: 归档
      url: /archives/ 
    - text: 项目
      url: //github.com/zhaoweiho
    - text: 关于
      url: /about/
    - text: 链接
      url: /link/
    - text: 订阅
      url: /feed.xml
    
url: "https://www.weiho.xyz"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  
