title: Weiho's Blog
description: 企业安全,代码审计,Web安全,Linux Hacking,安全架构,内网渗透,Weiho@secbug,Linux/Windows安全运维,安全开发
author: Weiho
github: https://github.com/zhaoweiho
about: Life is stuggle,try everything
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-weibo
      link: "https://weibo.com/l4c1fer"
    - icon: fa-twitter
      link: "#"
    - icon: fa-instagram
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "https://github.com/zhaoweiho"

urls:
    - text: Category
      url: /categories/
    - text: Archives
      url: /archives/ 
    - text: Projects
      url: //github.com/zhaoweiho
    - text: About
      url: /about/
    - text: Link
      url: /link/
    - text: RSS
      url: /feed.xml
    
url: "https://www.weiho.xyz"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  
